# Generated by Django 5.0.2 on 2025-03-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0005_maestros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materia',
            new_name='materias',
        ),
    ]
