# Generated by Django 5.0.2 on 2025-03-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0006_rename_materia_maestros_materias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='area',
            new_name='area_investigacion',
        ),
    ]
