# Generated by Django 5.0.2 on 2025-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0008_remove_maestros_materias_maestros_materias_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=255)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=255)),
                ('publico_json', models.TextField(blank=True, null=True)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('responsable_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('cupo', models.PositiveIntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
