# Generated by Django 5.0.2 on 2025-05-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0009_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='programa_educativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
